version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g pulp bower
        name: Install purescript
        command: |
          curl -sL https://github.com/purescript/purescript/releases/download/v0.12.5/linux64.tar.gz > /tmp/purescript.tar.gz
          tar -xvf /tmp/purescript.tar.gz
      - run: PATH=./purescript:$PATH pulp test
